# Generated by Django 4.2.6 on 2023-10-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Olympiads',
            fields=[
                ('id_olympiad', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dates_of_event', models.CharField(max_length=100)),
                ('dates_of_registration', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('selected_subject', models.JSONField()),
                ('selected_olympiad', models.JSONField()),
                ('number_class', models.IntegerField()),
                ('letter_of_class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id_result', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=100)),
                ('id_olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiads')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.students')),
            ],
        ),
        migrations.AddField(
            model_name='olympiads',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.subjects'),
        ),
    ]
